services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql

  airflow-init:
    image: apache/airflow:2.10.3
    container_name: airflow-init
    command: "db init"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "mysql+mysqldb://${MYSQL_AIRFLOW_USER}:${MYSQL_AIRFLOW_PASSWORD}@mysql:3306/${MYSQL_AIRFLOW_DATABASE}"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "5VZVLaD8KTHuKDiYHN3cMQ=="
      AIRFLOW__API__INTERNAL_API_SECRET_KEY: "5VZVLaD8KTHuKDiYHN3cMQ=="
    volumes:
      - ${AIRFLOW_DAGS_FOLDER}:/opt/airflow/dags

  airflow-webserver:
    image: apache/airflow:2.10.3
    container_name: airflow-webserver
    command: "webserver"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "mysql+mysqldb://${MYSQL_AIRFLOW_USER}:${MYSQL_AIRFLOW_PASSWORD}@mysql:3306/${MYSQL_AIRFLOW_DATABASE}"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "mysqlclient"
      AIRFLOW__WEBSERVER__SECRET_KEY: "5VZVLaD8KTHuKDiYHN3cMQ=="
      AIRFLOW__API__INTERNAL_API_SECRET_KEY: "5VZVLaD8KTHuKDiYHN3cMQ=="
    ports:
      - "${AIRFLOW_WEBSERVER_PORT}:8080"
    volumes:
      - ${AIRFLOW_DAGS_FOLDER}:/opt/airflow/dags
      - ${LOAD_PATH}:/files

  airflow-scheduler:
    image: apache/airflow:2.10.3
    container_name: airflow-scheduler
    command: "scheduler"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "mysql+mysqldb://${MYSQL_AIRFLOW_USER}:${MYSQL_AIRFLOW_PASSWORD}@mysql:3306/${MYSQL_AIRFLOW_DATABASE}"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "5VZVLaD8KTHuKDiYHN3cMQ=="
      AIRFLOW__API__INTERNAL_API_SECRET_KEY: "5VZVLaD8KTHuKDiYHN3cMQ=="
    volumes:
      - ${AIRFLOW_DAGS_FOLDER}:/opt/airflow/dags
      - ${LOAD_PATH}:/files